
GRANT CONNECT TO [polaris]
GO
GRANT CONNECT TO [CONTENTPROJECT\abaker]
GO
GRANT CONNECT TO [CONTENTPROJECT\acedeno]
GO
GRANT CONNECT TO [contentproject\hmadrigal]
GO
GRANT CONNECT TO [polaris]
GO
GRANT CONNECT TO [CONTENTPROJECT\abaker]
GO
GRANT CONNECT TO [CONTENTPROJECT\acedeno]
GO
GRANT CONNECT TO [contentproject\hmadrigal]

GO
