#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polaris.Dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Polaris")]
	public partial class SourceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDeveloper(Developer instance);
    partial void UpdateDeveloper(Developer instance);
    partial void DeleteDeveloper(Developer instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertDevelopmentTeam(DevelopmentTeam instance);
    partial void UpdateDevelopmentTeam(DevelopmentTeam instance);
    partial void DeleteDevelopmentTeam(DevelopmentTeam instance);
    partial void InsertGame(Game instance);
    partial void UpdateGame(Game instance);
    partial void DeleteGame(Game instance);
    partial void InsertPlayLog(PlayLog instance);
    partial void UpdatePlayLog(PlayLog instance);
    partial void DeletePlayLog(PlayLog instance);
    partial void InsertTimePeriod(TimePeriod instance);
    partial void UpdateTimePeriod(TimePeriod instance);
    partial void DeleteTimePeriod(TimePeriod instance);
    #endregion
		
		public SourceDataContext() : 
				base(global::Polaris.Dal.Properties.Settings.Default.PolarisConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SourceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SourceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SourceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SourceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Developer> Developers
		{
			get
			{
				return this.GetTable<Developer>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<DevelopmentTeam> DevelopmentTeams
		{
			get
			{
				return this.GetTable<DevelopmentTeam>();
			}
		}
		
		public System.Data.Linq.Table<Game> Games
		{
			get
			{
				return this.GetTable<Game>();
			}
		}
		
		public System.Data.Linq.Table<PlayLog> PlayLogs
		{
			get
			{
				return this.GetTable<PlayLog>();
			}
		}
		
		public System.Data.Linq.Table<TimePeriod> TimePeriods
		{
			get
			{
				return this.GetTable<TimePeriod>();
			}
		}
	}
	
	[Table(Name="Polaris.Developer")]
	public partial class Developer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DeveloperId;
		
		private int _UserId;
		
		private int _DevelopmentTeamId;
		
		private EntityRef<User> _User;
		
		private EntityRef<DevelopmentTeam> _DevelopmentTeam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeveloperIdChanging(int value);
    partial void OnDeveloperIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnDevelopmentTeamIdChanging(int value);
    partial void OnDevelopmentTeamIdChanged();
    #endregion
		
		public Developer()
		{
			this._User = default(EntityRef<User>);
			this._DevelopmentTeam = default(EntityRef<DevelopmentTeam>);
			OnCreated();
		}
		
		[Column(Storage="_DeveloperId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DeveloperId
		{
			get
			{
				return this._DeveloperId;
			}
			set
			{
				if ((this._DeveloperId != value))
				{
					this.OnDeveloperIdChanging(value);
					this.SendPropertyChanging();
					this._DeveloperId = value;
					this.SendPropertyChanged("DeveloperId");
					this.OnDeveloperIdChanged();
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_DevelopmentTeamId", DbType="Int NOT NULL")]
		public int DevelopmentTeamId
		{
			get
			{
				return this._DevelopmentTeamId;
			}
			set
			{
				if ((this._DevelopmentTeamId != value))
				{
					if (this._DevelopmentTeam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDevelopmentTeamIdChanging(value);
					this.SendPropertyChanging();
					this._DevelopmentTeamId = value;
					this.SendPropertyChanged("DevelopmentTeamId");
					this.OnDevelopmentTeamIdChanged();
				}
			}
		}
		
		[Association(Name="User_Developer", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public User RelatedUser
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Developers.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Developers.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("RelatedUser");
				}
			}
		}
		
		[Association(Name="DevelopmentTeam_Developer", Storage="_DevelopmentTeam", ThisKey="DevelopmentTeamId", OtherKey="DevelopmentTeamId", IsForeignKey=true)]
		public DevelopmentTeam RelatedDevelopmentTeam
		{
			get
			{
				return this._DevelopmentTeam.Entity;
			}
			set
			{
				DevelopmentTeam previousValue = this._DevelopmentTeam.Entity;
				if (((previousValue != value) 
							|| (this._DevelopmentTeam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DevelopmentTeam.Entity = null;
						previousValue.Developers.Remove(this);
					}
					this._DevelopmentTeam.Entity = value;
					if ((value != null))
					{
						value.Developers.Add(this);
						this._DevelopmentTeamId = value.DevelopmentTeamId;
					}
					else
					{
						this._DevelopmentTeamId = default(int);
					}
					this.SendPropertyChanged("RelatedDevelopmentTeam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="Polaris.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _Username;
		
		private string _Password;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private bool _Active;
		
		private int _PlayCredits;
		
		private int _RankingCredits;
		
		private EntitySet<Developer> _Developers;
		
		private EntitySet<PlayLog> _PlayLogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnPlayCreditsChanging(int value);
    partial void OnPlayCreditsChanged();
    partial void OnRankingCreditsChanging(int value);
    partial void OnRankingCreditsChanged();
    #endregion
		
		public User()
		{
			this._Developers = new EntitySet<Developer>(new Action<Developer>(this.attach_Developers), new Action<Developer>(this.detach_Developers));
			this._PlayLogs = new EntitySet<PlayLog>(new Action<PlayLog>(this.attach_PlayLogs), new Action<PlayLog>(this.detach_PlayLogs));
			OnCreated();
		}
		
		[Column(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_Username", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[Column(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_FirstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[Column(Storage="_LastName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[Column(Storage="_PlayCredits", DbType="Int NOT NULL")]
		public int PlayCredits
		{
			get
			{
				return this._PlayCredits;
			}
			set
			{
				if ((this._PlayCredits != value))
				{
					this.OnPlayCreditsChanging(value);
					this.SendPropertyChanging();
					this._PlayCredits = value;
					this.SendPropertyChanged("PlayCredits");
					this.OnPlayCreditsChanged();
				}
			}
		}
		
		[Column(Storage="_RankingCredits", DbType="Int NOT NULL")]
		public int RankingCredits
		{
			get
			{
				return this._RankingCredits;
			}
			set
			{
				if ((this._RankingCredits != value))
				{
					this.OnRankingCreditsChanging(value);
					this.SendPropertyChanging();
					this._RankingCredits = value;
					this.SendPropertyChanged("RankingCredits");
					this.OnRankingCreditsChanged();
				}
			}
		}
		
		[Association(Name="User_Developer", Storage="_Developers", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<Developer> Developers
		{
			get
			{
				return this._Developers;
			}
			set
			{
				this._Developers.Assign(value);
			}
		}
		
		[Association(Name="User_PlayLog", Storage="_PlayLogs", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<PlayLog> PlayLogs
		{
			get
			{
				return this._PlayLogs;
			}
			set
			{
				this._PlayLogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Developers(Developer entity)
		{
			this.SendPropertyChanging();
			entity.RelatedUser = this;
		}
		
		private void detach_Developers(Developer entity)
		{
			this.SendPropertyChanging();
			entity.RelatedUser = null;
		}
		
		private void attach_PlayLogs(PlayLog entity)
		{
			this.SendPropertyChanging();
			entity.RelatedUser = this;
		}
		
		private void detach_PlayLogs(PlayLog entity)
		{
			this.SendPropertyChanging();
			entity.RelatedUser = null;
		}
	}
	
	[Table(Name="Polaris.DevelopmentTeam")]
	public partial class DevelopmentTeam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DevelopmentTeamId;
		
		private string _Name;
		
		private System.Guid _Key;
		
		private EntitySet<Developer> _Developers;
		
		private EntitySet<Game> _Games;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDevelopmentTeamIdChanging(int value);
    partial void OnDevelopmentTeamIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnKeyChanging(System.Guid value);
    partial void OnKeyChanged();
    #endregion
		
		public DevelopmentTeam()
		{
			this._Developers = new EntitySet<Developer>(new Action<Developer>(this.attach_Developers), new Action<Developer>(this.detach_Developers));
			this._Games = new EntitySet<Game>(new Action<Game>(this.attach_Games), new Action<Game>(this.detach_Games));
			OnCreated();
		}
		
		[Column(Storage="_DevelopmentTeamId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DevelopmentTeamId
		{
			get
			{
				return this._DevelopmentTeamId;
			}
			set
			{
				if ((this._DevelopmentTeamId != value))
				{
					this.OnDevelopmentTeamIdChanging(value);
					this.SendPropertyChanging();
					this._DevelopmentTeamId = value;
					this.SendPropertyChanged("DevelopmentTeamId");
					this.OnDevelopmentTeamIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Name="[Key]", Storage="_Key", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this.OnKeyChanging(value);
					this.SendPropertyChanging();
					this._Key = value;
					this.SendPropertyChanged("Key");
					this.OnKeyChanged();
				}
			}
		}
		
		[Association(Name="DevelopmentTeam_Developer", Storage="_Developers", ThisKey="DevelopmentTeamId", OtherKey="DevelopmentTeamId")]
		public EntitySet<Developer> Developers
		{
			get
			{
				return this._Developers;
			}
			set
			{
				this._Developers.Assign(value);
			}
		}
		
		[Association(Name="DevelopmentTeam_Game", Storage="_Games", ThisKey="DevelopmentTeamId", OtherKey="DevelopmentTeamId")]
		public EntitySet<Game> Games
		{
			get
			{
				return this._Games;
			}
			set
			{
				this._Games.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Developers(Developer entity)
		{
			this.SendPropertyChanging();
			entity.RelatedDevelopmentTeam = this;
		}
		
		private void detach_Developers(Developer entity)
		{
			this.SendPropertyChanging();
			entity.RelatedDevelopmentTeam = null;
		}
		
		private void attach_Games(Game entity)
		{
			this.SendPropertyChanging();
			entity.RelatedDevelopmentTeam = this;
		}
		
		private void detach_Games(Game entity)
		{
			this.SendPropertyChanging();
			entity.RelatedDevelopmentTeam = null;
		}
	}
	
	[Table(Name="Polaris.Game")]
	public partial class Game : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GameId;
		
		private string _Name;
		
		private System.Guid _Key;
		
		private bool _Active;
		
		private int _DevelopmentTeamId;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private System.Nullable<System.DateTime> _FeaturedStartDate;
		
		private System.Nullable<System.DateTime> _FeaturedEndDate;
		
		private EntitySet<PlayLog> _PlayLogs;
		
		private EntityRef<DevelopmentTeam> _DevelopmentTeam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGameIdChanging(int value);
    partial void OnGameIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnKeyChanging(System.Guid value);
    partial void OnKeyChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnDevelopmentTeamIdChanging(int value);
    partial void OnDevelopmentTeamIdChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    partial void OnFeaturedStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFeaturedStartDateChanged();
    partial void OnFeaturedEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFeaturedEndDateChanged();
    #endregion
		
		public Game()
		{
			this._PlayLogs = new EntitySet<PlayLog>(new Action<PlayLog>(this.attach_PlayLogs), new Action<PlayLog>(this.detach_PlayLogs));
			this._DevelopmentTeam = default(EntityRef<DevelopmentTeam>);
			OnCreated();
		}
		
		[Column(Storage="_GameId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GameId
		{
			get
			{
				return this._GameId;
			}
			set
			{
				if ((this._GameId != value))
				{
					this.OnGameIdChanging(value);
					this.SendPropertyChanging();
					this._GameId = value;
					this.SendPropertyChanged("GameId");
					this.OnGameIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Name="[Key]", Storage="_Key", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this.OnKeyChanging(value);
					this.SendPropertyChanging();
					this._Key = value;
					this.SendPropertyChanged("Key");
					this.OnKeyChanged();
				}
			}
		}
		
		[Column(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[Column(Storage="_DevelopmentTeamId", DbType="Int NOT NULL")]
		public int DevelopmentTeamId
		{
			get
			{
				return this._DevelopmentTeamId;
			}
			set
			{
				if ((this._DevelopmentTeamId != value))
				{
					if (this._DevelopmentTeam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDevelopmentTeamIdChanging(value);
					this.SendPropertyChanging();
					this._DevelopmentTeamId = value;
					this.SendPropertyChanged("DevelopmentTeamId");
					this.OnDevelopmentTeamIdChanged();
				}
			}
		}
		
		[Column(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[Column(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[Column(Storage="_FeaturedStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FeaturedStartDate
		{
			get
			{
				return this._FeaturedStartDate;
			}
			set
			{
				if ((this._FeaturedStartDate != value))
				{
					this.OnFeaturedStartDateChanging(value);
					this.SendPropertyChanging();
					this._FeaturedStartDate = value;
					this.SendPropertyChanged("FeaturedStartDate");
					this.OnFeaturedStartDateChanged();
				}
			}
		}
		
		[Column(Storage="_FeaturedEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FeaturedEndDate
		{
			get
			{
				return this._FeaturedEndDate;
			}
			set
			{
				if ((this._FeaturedEndDate != value))
				{
					this.OnFeaturedEndDateChanging(value);
					this.SendPropertyChanging();
					this._FeaturedEndDate = value;
					this.SendPropertyChanged("FeaturedEndDate");
					this.OnFeaturedEndDateChanged();
				}
			}
		}
		
		[Association(Name="Game_PlayLog", Storage="_PlayLogs", ThisKey="GameId", OtherKey="GameId")]
		public EntitySet<PlayLog> PlayLogs
		{
			get
			{
				return this._PlayLogs;
			}
			set
			{
				this._PlayLogs.Assign(value);
			}
		}
		
		[Association(Name="DevelopmentTeam_Game", Storage="_DevelopmentTeam", ThisKey="DevelopmentTeamId", OtherKey="DevelopmentTeamId", IsForeignKey=true)]
		public DevelopmentTeam RelatedDevelopmentTeam
		{
			get
			{
				return this._DevelopmentTeam.Entity;
			}
			set
			{
				DevelopmentTeam previousValue = this._DevelopmentTeam.Entity;
				if (((previousValue != value) 
							|| (this._DevelopmentTeam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DevelopmentTeam.Entity = null;
						previousValue.Games.Remove(this);
					}
					this._DevelopmentTeam.Entity = value;
					if ((value != null))
					{
						value.Games.Add(this);
						this._DevelopmentTeamId = value.DevelopmentTeamId;
					}
					else
					{
						this._DevelopmentTeamId = default(int);
					}
					this.SendPropertyChanged("RelatedDevelopmentTeam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PlayLogs(PlayLog entity)
		{
			this.SendPropertyChanging();
			entity.RelatedGame = this;
		}
		
		private void detach_PlayLogs(PlayLog entity)
		{
			this.SendPropertyChanging();
			entity.RelatedGame = null;
		}
	}
	
	[Table(Name="Polaris.PlayLog")]
	public partial class PlayLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PlayLogId;
		
		private int _GameId;
		
		private int _UserId;
		
		private System.DateTime _Date;
		
		private decimal _Score;
		
		private EntityRef<Game> _Game;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlayLogIdChanging(int value);
    partial void OnPlayLogIdChanged();
    partial void OnGameIdChanging(int value);
    partial void OnGameIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnScoreChanging(decimal value);
    partial void OnScoreChanged();
    #endregion
		
		public PlayLog()
		{
			this._Game = default(EntityRef<Game>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[Column(Storage="_PlayLogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PlayLogId
		{
			get
			{
				return this._PlayLogId;
			}
			set
			{
				if ((this._PlayLogId != value))
				{
					this.OnPlayLogIdChanging(value);
					this.SendPropertyChanging();
					this._PlayLogId = value;
					this.SendPropertyChanged("PlayLogId");
					this.OnPlayLogIdChanged();
				}
			}
		}
		
		[Column(Storage="_GameId", DbType="Int NOT NULL")]
		public int GameId
		{
			get
			{
				return this._GameId;
			}
			set
			{
				if ((this._GameId != value))
				{
					if (this._Game.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGameIdChanging(value);
					this.SendPropertyChanging();
					this._GameId = value;
					this.SendPropertyChanged("GameId");
					this.OnGameIdChanged();
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[Column(Storage="_Score", DbType="Decimal(18,0) NOT NULL")]
		public decimal Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[Association(Name="Game_PlayLog", Storage="_Game", ThisKey="GameId", OtherKey="GameId", IsForeignKey=true)]
		public Game RelatedGame
		{
			get
			{
				return this._Game.Entity;
			}
			set
			{
				Game previousValue = this._Game.Entity;
				if (((previousValue != value) 
							|| (this._Game.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Game.Entity = null;
						previousValue.PlayLogs.Remove(this);
					}
					this._Game.Entity = value;
					if ((value != null))
					{
						value.PlayLogs.Add(this);
						this._GameId = value.GameId;
					}
					else
					{
						this._GameId = default(int);
					}
					this.SendPropertyChanged("RelatedGame");
				}
			}
		}
		
		[Association(Name="User_PlayLog", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public User RelatedUser
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.PlayLogs.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.PlayLogs.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("RelatedUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="Polaris.TimePeriod")]
	public partial class TimePeriod : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TimePeriodId;
		
		private string _Name;
		
		private int _Hours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTimePeriodIdChanging(int value);
    partial void OnTimePeriodIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHoursChanging(int value);
    partial void OnHoursChanged();
    #endregion
		
		public TimePeriod()
		{
			OnCreated();
		}
		
		[Column(Storage="_TimePeriodId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TimePeriodId
		{
			get
			{
				return this._TimePeriodId;
			}
			set
			{
				if ((this._TimePeriodId != value))
				{
					this.OnTimePeriodIdChanging(value);
					this.SendPropertyChanging();
					this._TimePeriodId = value;
					this.SendPropertyChanged("TimePeriodId");
					this.OnTimePeriodIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Hours", DbType="Int NOT NULL")]
		public int Hours
		{
			get
			{
				return this._Hours;
			}
			set
			{
				if ((this._Hours != value))
				{
					this.OnHoursChanging(value);
					this.SendPropertyChanging();
					this._Hours = value;
					this.SendPropertyChanged("Hours");
					this.OnHoursChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
